"""Add file_hash to Report model

Revision ID: 680a7657233d
Revises: a7160695045f
Create Date: 2025-06-19 14:22:40.877020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '680a7657233d'
down_revision: Union[str, None] = 'a7160695045f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('file_hash', sa.String(), nullable=False))
    op.create_unique_constraint('_user_file_hash_uc', 'reports', ['user_id', 'file_hash'])
    op.create_index(op.f('ix_reports_file_hash'), 'reports', ['file_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reports_file_hash'), table_name='reports')
    op.drop_constraint('_user_file_hash_uc', 'reports', type_='unique')
    op.drop_column('reports', 'file_hash')
    # ### end Alembic commands ###
